
name: benchmarks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -e .[benchmark]
          ls
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Run benchmarks
        run: |
          asv machine --yes
          asv run
      - name: Checkout benchmarks remote branch
        run: |
          git fetch origin
          git switch benchmarks
          git rebase origin/main
      - name: Commit new results to the benchmarks branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .asv/results
          git commit -m "benchmark results" .asv/results
          git push
      - name: Build HTML website from benchmark results
        run: |
          asv publish
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .asv/html/


  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2